import { pool } from '../db/pool';

const AREA_DELTA_TOLERANCE_M2 = 0.01; // numeric rounding only: loaded geometry is a byte-for-byte passthrough of source geometry (same SRID, no reprojection), so any delta above float/numeric rounding noise would indicate an unintended transform.
const CENTROID_DISPLACEMENT_TOLERANCE_M = 0.01; // same rationale as above, expressed in metres (EPSG:32736 is a metric projection).
const SAMPLE_SIZE = 10000;

async function main() {
  const client = await pool.connect();
  try {
    const totals = await client.query(`
      SELECT
        (SELECT count(*) FROM source_parcel) AS source_total,
        (SELECT count(*) FROM parcel) AS target_total,
        (SELECT count(*) FROM quarantine_record) AS quarantined_total
    `);
    const { source_total, target_total, quarantined_total } = totals.rows[0];

    const byAdminUnit = await client.query(`
      SELECT COALESCE(s.district_code, '(null)') AS district_code,
             count(s.*)::bigint AS source_count,
             count(p.id)::bigint AS target_count,
             count(q.id)::bigint AS quarantined_count
      FROM source_parcel s
      LEFT JOIN parcel p ON p.source_src_id = s.src_id
      LEFT JOIN quarantine_record q ON q.source_src_id = s.src_id
      GROUP BY 1 ORDER BY 1
    `);

    const upiSourceMinusTarget = await client.query(`
      SELECT s.upi, count(*) AS occurrences
      FROM source_parcel s
      WHERE s.upi IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM parcel p WHERE p.upi = s.upi)
      GROUP BY s.upi
      ORDER BY s.upi
    `);

    const upiTargetMinusSource = await client.query(`
      SELECT p.upi
      FROM parcel p
      WHERE NOT EXISTS (SELECT 1 FROM source_parcel s WHERE s.upi = p.upi)
      ORDER BY p.upi
    `);

    const missingUpiCount = await client.query(`SELECT count(*)::bigint AS n FROM source_parcel WHERE upi IS NULL`);

    const quarantineByRule = await client.query(`
      SELECT rule_violated, count(*)::bigint AS n
      FROM quarantine_record GROUP BY rule_violated ORDER BY rule_violated
    `);

    const areaAndCentroid = await client.query(
      `
      WITH sample AS (
        SELECT p.id, p.source_src_id, p.geom AS target_geom, p.area_computed AS target_area,
               s.geom AS source_geom
        FROM parcel p
        JOIN source_parcel s ON s.src_id = p.source_src_id
        ORDER BY p.id
        LIMIT $1
      )
      SELECT
        count(*)::bigint AS sample_size,
        max(abs(target_area - ST_Area(source_geom))) AS max_area_delta_m2,
        avg(abs(target_area - ST_Area(source_geom))) AS avg_area_delta_m2,
        sum(target_area) AS sum_target_area_m2,
        sum(ST_Area(source_geom)) AS sum_source_area_m2,
        max(ST_Distance(ST_Centroid(target_geom), ST_Centroid(source_geom))) AS max_centroid_displacement_m,
        avg(ST_Distance(ST_Centroid(target_geom), ST_Centroid(source_geom))) AS avg_centroid_displacement_m
      FROM sample
      `,
      [SAMPLE_SIZE],
    );
    const ac = areaAndCentroid.rows[0];

    const quarantineSamples = await client.query(`
      SELECT source_src_id, upi_attempted, rule_violated, detail
      FROM quarantine_record ORDER BY rule_violated, source_src_id LIMIT 12
    `);

    const rowCountsMatch = Number(source_total) === Number(target_total) + Number(quarantined_total);

    const lines: string[] = [];
    lines.push('# RECONCILIATION.md — Task 1 legacy load proof');
    lines.push('');
    lines.push(`Generated by \`npm run reconcile\` against a live database on ${new Date().toISOString()}.`);
    lines.push('All numbers below come from querying `source_parcel`, `parcel`, and `quarantine_record` directly after running `npm run load` — nothing here is estimated.');
    lines.push('');
    lines.push('## 1. Row counts');
    lines.push('');
    lines.push(`| | Count |`);
    lines.push(`|---|---|`);
    lines.push(`| source_parcel (legacy extract) | ${source_total} |`);
    lines.push(`| parcel (loaded, target) | ${target_total} |`);
    lines.push(`| quarantine_record | ${quarantined_total} |`);
    lines.push(`| source = target + quarantined ? | **${rowCountsMatch ? 'YES — exact match' : 'NO — see below, investigate'}** |`);
    lines.push('');
    lines.push('Tolerance: **0 rows** — every source row must land in exactly one of `parcel` or `quarantine_record`. This is an exact-match invariant, not a statistical tolerance, because every legacy row must be accounted for somewhere.');
    lines.push('');
    lines.push('### By administrative unit (district_code)');
    lines.push('');
    lines.push('| District | Source | Loaded | Quarantined |');
    lines.push('|---|---|---|---|');
    for (const r of byAdminUnit.rows) {
      lines.push(`| ${r.district_code} | ${r.source_count} | ${r.target_count} | ${r.quarantined_count} |`);
    }
    lines.push('');

    lines.push('## 2. UPI set equality (both directions)');
    lines.push('');
    const missingUpiN = Number(missingUpiCount.rows[0].n);
    lines.push(
      missingUpiN === 0
        ? '`source_parcel.upi` has no NULL values in this dataset, so every source row participates in the UPI set comparison below.'
        : `${missingUpiN} source rows have a NULL upi and are excluded from the UPI set comparison below — they are quarantined under \`missing_upi\` and counted in Section 3 instead.`,
    );
    lines.push('');
    lines.push(`**Source − Target** (UPIs that exist in the legacy extract but never reached \`parcel\`): **${upiSourceMinusTarget.rows.length} distinct UPIs**.`);
    lines.push('Explanation: this is expected to equal the number of *distinct* UPIs whose *every* occurrence was quarantined — in this dataset, the ~400 self-intersecting "bowtie" rows (`unrepairable_invalid_geometry`), each of which has a UPI unique to itself, so all of them disappear from the target UPI set. UPIs affected only by `duplicate_upi` quarantine are **not** in this set, because the earliest occurrence under that UPI is still loaded.');
    if (upiSourceMinusTarget.rows.length) {
      lines.push('');
      lines.push('First 10 examples: ' + upiSourceMinusTarget.rows.slice(0, 10).map((r) => r.upi).join(', '));
    }
    lines.push('');
    lines.push(`**Target − Source** (UPIs present in \`parcel\` that don't trace back to a source row): **${upiTargetMinusSource.rows.length} distinct UPIs**.`);
    lines.push('Explanation: expected to be exactly 0 for a pure legacy load — every loaded UPI is copied verbatim from `source_parcel.upi` and no new UPIs are minted during the load (new UPIs are only minted by the subdivision transaction, which runs afterwards and is out of scope for this reconciliation of the *legacy load*).');
    lines.push('');

    lines.push('## 3. Quarantine, accounted for');
    lines.push('');
    lines.push('| Rule violated | Count |');
    lines.push('|---|---|');
    for (const r of quarantineByRule.rows) lines.push(`| ${r.rule_violated} | ${r.n} |`);
    lines.push('');
    lines.push('Sample quarantined records (first 12, ordered by rule):');
    lines.push('');
    lines.push('| source_src_id | upi_attempted | rule_violated | detail |');
    lines.push('|---|---|---|---|');
    for (const r of quarantineSamples.rows) {
      lines.push(`| ${r.source_src_id} | ${r.upi_attempted ?? '(null)'} | ${r.rule_violated} | ${r.detail} |`);
    }
    lines.push('');

    lines.push('## 4. Area deltas and centroid displacement');
    lines.push('');
    lines.push(`Sampled ${ac.sample_size} loaded parcels (first ${SAMPLE_SIZE} by id) and compared each against its source row (matched by \`source_src_id\`):`);
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|---|---|');
    lines.push(`| Sum of target area_computed (sample) | ${Number(ac.sum_target_area_m2).toFixed(2)} m² |`);
    lines.push(`| Sum of ST_Area(source geom) (sample) | ${Number(ac.sum_source_area_m2).toFixed(2)} m² |`);
    lines.push(`| Max per-parcel area delta | ${Number(ac.max_area_delta_m2).toFixed(6)} m² |`);
    lines.push(`| Avg per-parcel area delta | ${Number(ac.avg_area_delta_m2).toFixed(6)} m² |`);
    lines.push(`| Max centroid displacement | ${Number(ac.max_centroid_displacement_m).toFixed(6)} m |`);
    lines.push(`| Avg centroid displacement | ${Number(ac.avg_centroid_displacement_m).toFixed(6)} m |`);
    lines.push('');
    lines.push(`Tolerances: **${AREA_DELTA_TOLERANCE_M2} m²** for area delta, **${CENTROID_DISPLACEMENT_TOLERANCE_M} m** for centroid displacement.`);
    lines.push('Why these numbers: the load never reprojects or re-derives geometry for a row that passes validation — the target `geom` is the source `geom` verbatim (same EPSG:32736 SRID). So area/centroid should match to floating-point/`numeric` rounding noise only. Any delta above these thresholds would mean the load pipeline is silently mutating geometry, which is a hard failure worth investigating, not a data-quality nuance.');
    lines.push(`Result: max area delta ${Number(ac.max_area_delta_m2) <= AREA_DELTA_TOLERANCE_M2 ? 'is within' : 'EXCEEDS'} tolerance; max centroid displacement ${Number(ac.max_centroid_displacement_m) <= CENTROID_DISPLACEMENT_TOLERANCE_M ? 'is within' : 'EXCEEDS'} tolerance.`);
    lines.push('');
    lines.push('Note: this reconciliation deliberately does *not* compare `declared_area` to computed area — that divergence is a pre-existing legacy data-quality defect (the seed\'s "area mismatch" injection), not a load-fidelity issue, and is reported instead by `GET /qa/report`.');
    lines.push('');

    // Prints Markdown to stdout only (works identically run from the host or
    // via `docker compose exec`); redirect it to the file yourself:
    //   npm run reconcile > ../RECONCILIATION.md
    process.stdout.write(lines.join('\n') + '\n');
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
